# Generated by Django 2.0 on 2017-12-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171206_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='about',
            new_name='content',
        ),
    ]
